import '../models/sediment_feature.dart';

class SedimentRepository {
  static List<SedimentFeature> getAllFeatures() {
    // Create all individual features
    final features = [
      // Grain Outline Types (5)
      _createFeature(
        codeNumber: 'QMT-M-001',
        title: 'Grain Outline',
        type: 'Angular',
        agentsInvolved:
            'Limited Transportation and Crushing of grains. It depends on Distance, Time, Parent Rock and Original Size',
        morphologicalFeatures: 'Angular edges on outline',
        origin: 'Mechanical',
        factorsActing: 'Crushed, Limited Transportation',
        alteration: 'Solution and Precipitation',
        size: '',
        coverage: '',
        environment: 'Glacial, Low Energy Fluvial',
        imageRefs: ['1A.1', '1A.2', '1A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-002',
        title: 'Grain Outline',
        type: 'Sub Angular',
        agentsInvolved:
            'Transportation Mode, Distance, Time, Parent Rock, Original Size affects the grain. Alternative exposure causes sub angular features in grain.',
        morphologicalFeatures:
            'Mostly Angular along with rounded or smooth edges',
        origin: 'Mechanical',
        factorsActing: 'Alternative Exposure',
        alteration: 'Solution and Precipitation',
        size: '',
        coverage: '',
        environment: 'Fluvial, Marine, Littoral Dune',
        imageRefs: ['1B.1', '1B.2', '1B.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-003',
        title: 'Grain Outline',
        type: 'Rounded',
        agentsInvolved: '',
        morphologicalFeatures:
            'Rounded outline, surface is smooth with very few sharp edges',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['1C.1', '1C.2', '1C.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-004',
        title: 'Grain Outline',
        type: 'Well Rounded',
        agentsInvolved: '',
        morphologicalFeatures:
            'Completely smoothened surface with no sharp outline features visible',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['1D.1', '1D.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-005',
        title: 'Grain Outline',
        type: 'Sub Rounded',
        agentsInvolved: '',
        morphologicalFeatures:
            'Rounded or smooth edges dominate angular edges in the grain outline',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['1E.1', '1E.2', '1E.3'],
      ),

      // Conchoidal Fractures (6)
      _createFeature(
        codeNumber: 'QMT-M-006',
        title: 'Conchoidal Fractures',
        type: 'Straight',
        agentsInvolved:
            'Mineral Inclusion, weakening of crystal lattice or powerful impact or pressure on the grain surface causes fractures',
        morphologicalFeatures:
            'Shell-like breakage patterns, ribbed appearance due to pressure wave, fracture planes may contain arcuate and straight steps',
        origin: 'Mechanical',
        factorsActing: 'Powerful impact or pressure on the grain surface',
        alteration: '',
        size: '',
        coverage: '',
        environment: 'Littoral',
        imageRefs: ['2A.1'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-007',
        title: 'Conchoidal Fractures',
        type: 'Curved',
        agentsInvolved:
            'Mineral Inclusion, weakening of crystal lattice or powerful impact or pressure on the grain surface causes fractures',
        morphologicalFeatures:
            'Shell-like breakage patterns, ribbed appearance due to pressure wave, fracture planes may contain arcuate and straight steps',
        origin: 'Mechanical',
        factorsActing: 'Powerful impact or pressure on the grain surface',
        alteration: '',
        size: '',
        coverage: '',
        environment: 'Eolian',
        imageRefs: ['2B.1'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-008',
        title: 'Conchoidal Fractures',
        type: 'Mixed',
        agentsInvolved:
            'Mineral Inclusion, weakening of crystal lattice or powerful impact or pressure on the grain surface causes fractures',
        morphologicalFeatures:
            'Shell-like breakage patterns, ribbed appearance due to pressure wave, fracture planes may contain arcuate and straight steps',
        origin: 'Mechanical',
        factorsActing: 'Powerful impact or pressure on the grain surface',
        alteration: '',
        size: '',
        coverage: '50%',
        environment: '',
        imageRefs: ['2C.1', '2C.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-009',
        title: 'Conchoidal Fractures',
        type: 'Small',
        agentsInvolved:
            'Mineral Inclusion, weakening of crystal lattice or powerful impact or pressure on the grain surface causes fractures',
        morphologicalFeatures:
            'Shell-like breakage patterns, ribbed appearance due to pressure wave, fracture planes may contain arcuate and straight steps',
        origin: 'Mechanical',
        factorsActing: 'Powerful impact or pressure on the grain surface',
        alteration: '',
        size: '< 10 µm',
        coverage: '',
        environment: '',
        imageRefs: ['2D.1', '2D.2', '2D.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-010',
        title: 'Conchoidal Fractures',
        type: 'Medium',
        agentsInvolved:
            'Mineral Inclusion, weakening of crystal lattice or powerful impact or pressure on the grain surface causes fractures',
        morphologicalFeatures:
            'Shell-like breakage patterns, ribbed appearance due to pressure wave, fracture planes may contain arcuate and straight steps',
        origin: 'Mechanical',
        factorsActing: 'Powerful impact or pressure on the grain surface',
        alteration: '',
        size: '>10 µm - < 100 µm',
        coverage: '',
        environment: '',
        imageRefs: ['2E.1', '2E.2', '2E.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-011',
        title: 'Conchoidal Fractures',
        type: 'Large',
        agentsInvolved:
            'Mineral Inclusion, weakening of crystal lattice or powerful impact or pressure on the grain surface causes fractures',
        morphologicalFeatures:
            'Shell-like breakage patterns, ribbed appearance due to pressure wave, fracture planes may contain arcuate and straight steps',
        origin: 'Mechanical',
        factorsActing: 'Powerful impact or pressure on the grain surface',
        alteration: '',
        size: '> 100 µm',
        coverage: '',
        environment: '',
        imageRefs: ['2F.1', '2F.2', '2F.3'],
      ),

      // Steps (2)
      _createFeature(
        codeNumber: 'QMT-M-012',
        title: 'Steps',
        type: 'Arcuate',
        agentsInvolved: '',
        morphologicalFeatures:
            'Curved Step like features, observed on Conchoidal planes',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: 'between steps ~ 5 µm',
        coverage: '',
        environment: '',
        imageRefs: ['3A.1', '3A.2', '3A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-013',
        title: 'Steps',
        type: 'Straight',
        agentsInvolved: '',
        morphologicalFeatures:
            'Straight Step like features, observed on Conchoidal planes',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: 'between steps ~ 5 µm',
        coverage: '',
        environment: '',
        imageRefs: ['3B.1', '3B.2', '3B.3'],
      ),

      // Other Features (24)
      _createFeature(
        codeNumber: 'QMT-M-014',
        title: 'Meandering Ridges',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Wavy ridge running across grain surface, found in intersections of curved conchoidal fractures',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['4A.1', '4A.2', '4A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-015',
        title: 'Flat Cleavage Surface',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Breakage Patterns, parallel to cleavage planes r and z as these planes have few Si-O bonds',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['5A.1', '5A.2', '5A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-016',
        title: 'Graded Arcs',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Concentric Circular/Semicircular series of arcs. Each arc forms a fan shaped pattern',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '>400 µm',
        coverage: '5%',
        environment: '',
        imageRefs: ['6A.1', '6A.2', '6A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-017',
        title: 'V-Shaped Percussion Cracks',
        type: '',
        agentsInvolved: 'Reworking, Transport, Distance and Time',
        morphologicalFeatures:
            'The depressions become narrower as they penetrate deeper into the grain until they finally vanish. The triangular shape is an expression of the underlying cleavage plate edges',
        origin: 'Mechanical',
        factorsActing: 'Randomly oriented collisions',
        alteration: '',
        size: 'Max. diameter: 5 µm, Max. Depth: 0.1 µm',
        coverage: '',
        environment:
            'Littoral, Braided Rivers, Glacio-Fluvial, High energy subaqueous',
        imageRefs: ['7A.1', '7A.2', '7A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-018',
        title: 'Grooves and Scratches',
        type: 'Linear/ Straight',
        agentsInvolved: '',
        morphologicalFeatures:
            'Distinctly linear, Deep elongated troughs or depressions',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['8A.1', '8A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-019',
        title: 'Grooves and Scratches',
        type: 'Curved',
        agentsInvolved: '',
        morphologicalFeatures: 'Deep elongated troughs or depressions',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['8B.1', '8B.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-020',
        title: 'Upturned Plates',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Thin Parallel plates oriented at angles, irregular, jagged outline and broken. Plates are oriented to r,z,and m faces',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: 'length: 0.5-10 µm, thickness: 2-20 µm',
        coverage: '',
        environment: '',
        imageRefs: ['9A.1', '9A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-021',
        title: 'Crescentic Percussion Marks',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Crescent shaped marks, fracture not developed fully',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: 'distance between corners 1-20 µm',
        coverage: '10-40%',
        environment: '',
        imageRefs: ['10A.1', '10A.2', '10A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-022',
        title: 'Bulbous Edges',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Prominent protrusions resembling parabolic curve, occurs along with smoothed over or polished elongated depressions',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['11A.1', '11A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-023',
        title: 'Abrasion Fatigue',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Reactive surface layer contains cracks and dislocations with small grains attached sometimes',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['12A.1', '12A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-024',
        title: 'Parallel Striations/Ridges',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Linear or curved Marks, Elongated depressions. Ridges places between depressions, its lengthier',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '~20–250 mm, ~0.5-10 µm apart',
        coverage: '',
        environment: '',
        imageRefs: ['13A.1', '13A.2', '13A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-025',
        title: 'Imbricated Grinding Features',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Circular, Subcircular, steeply dipping hogback ridges',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['14A.1'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-026',
        title: 'Crescentic Gouges',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Crescent shaped and often deep gouges, with convex and concave limbs',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['15A.1'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-008',
        title: 'Halite Crystals',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures: 'Crystals of Halite adhering to the surface',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['16A.1', '16A.2', '16A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-027',
        title: 'Broken Edges',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Terminations in ends of the grains, characterised by scars or protrusions on the end',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['17A.1', '17A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-X-001',
        title: 'Smooth Surface',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Grain surfaces that look smoothened in certain planes or in patches',
        origin: 'Mechanical/Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['18A.1'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-001',
        title: 'Oriented Etch Pits',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Triangular, Rectangular depressions, distinguishable from V-shaped percussion cracks, perfectly oriented within a crystal plane',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size:
            '1-30 µm, apical and basal angle of triangular etch pits (38 to 45° and 65 to 70°, respectively)',
        coverage: '50%',
        environment: '',
        imageRefs: ['19A.1', '19A.2', '19A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-002',
        title: 'Solution Pits',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Circular, Subcircular and other shapes, extremely variable pitting, difficult to distinguish between remnants of mineral intrusion',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['20A.1', '20A.2', '20A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-004',
        title: 'Scaling',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Widespread surface disintegration, creating grain fragments and flakes',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['22A.1', '22A.2', '22A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-005',
        title: 'Silica Globules',
        type: '',
        agentsInvolved:
            'Forms when relatively immobile grains are in contact with super saturated fluids',
        morphologicalFeatures:
            'Circular to Subcircular droplet of silica precipitates',
        origin: 'Chemical',
        factorsActing: 'Alternative exposure and submerging',
        alteration: '',
        size: '0.05 - 0.25 µm',
        coverage: '',
        environment:
            'Intertidal Marine, Low energy Fluvial, Littoral Dune, Diagenetic',
        imageRefs: ['24A.1', '24A.2', '24A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-006',
        title: 'Silica Flowers',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Convex-upward, radial structures with hexagonal symmetry',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: '1 - 20 µm',
        coverage: '',
        environment: '',
        imageRefs: ['25A.1', '25A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-007',
        title: 'Silica Pellicles',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Smooth thin layer of silica precipitates, which obscures earlier microtextures',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: 'thickness: 2 to 10 µm',
        coverage: '',
        environment: '',
        imageRefs: ['26A.1', '26A.2', '26A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-008',
        title: 'Crystalline Overgrowth',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Thick layers of subhedral to euhedral mineral precipitations',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: 'thickness: ~10 µm',
        coverage: '',
        environment: '',
        imageRefs: ['27A.1', '27A.2', '27A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-X-003',
        title: 'Adhering Particles',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Fragments or particles attached to the grain, remnants of source rocks or diagenetic environments',
        origin: 'Mechanical/Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '10%',
        environment: '',
        imageRefs: ['28A.1', '28A.2', '28A.3'],
      ),

      // Relief (3)
      _createFeature(
        codeNumber: 'QMT-X-004',
        title: 'Relief',
        type: 'Low',
        agentsInvolved:
            'Diagenetic Environments, solution, precipitation and dissolution of protrusions',
        morphologicalFeatures: 'Nearly Smooth surface, lacks irregularities',
        origin: 'Mechanical & Chemical',
        factorsActing:
            'Diagenetic Environments, solution, precipitation and dissolution of protrusions',
        alteration: '',
        size: '',
        coverage: '',
        environment: 'Eolian, High Energy fluvial',
        imageRefs: ['29A.1', '29A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-X-005',
        title: 'Relief',
        type: 'Medium',
        agentsInvolved: '',
        morphologicalFeatures: 'Semi Smooth Surfaces',
        origin: 'Mechanical & Chemical',
        factorsActing: '',
        alteration: '',
        size: '<1 µm sized irregularities',
        coverage: '',
        environment: '',
        imageRefs: ['29B.1'],
      ),
      _createFeature(
        codeNumber: 'QMT-X-006',
        title: 'Relief',
        type: 'High',
        agentsInvolved: '',
        morphologicalFeatures:
            'Irregular surface, has pronounced swells and swales',
        origin: 'Mechanical & Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['29C.1', '29C.2', '29C.3'],
      ),

      // Additional Features (9)
      _createFeature(
        codeNumber: 'QMT-X-007',
        title: 'Elongated Depressions',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Situated between parallel ridges or occur singularly, sometimes found in dish shaped, often occur along with bulbous edges',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: '20-250 µm',
        coverage: '',
        environment: '',
        imageRefs: ['30A.1', '30A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-X-008',
        title: 'Chattermarks',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'These are a series of linearly arranged, straight to slightly curved grooves on surfaces of mineral grains lacking clear expression of cleavage. Resemblance to a fishbone pattern, individual trails are randomly oriented across the grain surface and indentations',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: 'depth: <5 µm, length: 1 to 50 μm',
        coverage: '',
        environment: '',
        imageRefs: ['31A.1', '31A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-X-011',
        title: 'Cracks',
        type: 'Polygonal',
        agentsInvolved: '',
        morphologicalFeatures:
            'Brittle, irregular outline, with varied lengths',
        origin: 'Mechanical',
        factorsActing: '',
        alteration: '',
        size: 'Length: 1 - 50 μm',
        coverage: '',
        environment: '',
        imageRefs: ['32C.1', '32C.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-009',
        title: 'Trapped Diatoms',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Siliceous skeleton of photosynthesising algae, found in almost all environments, trapped in the sediment',
        origin: 'Biological',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['34A.1', '34A.2', '34A.3'],
      ),

      // Pits (3)
      _createFeature(
        codeNumber: 'QMT-M-030',
        title: 'Pits',
        type: 'Small',
        agentsInvolved: '',
        morphologicalFeatures:
            'Pits of different shapes, distributed on the grain',
        origin: 'Mechanical/Chemical',
        factorsActing: '',
        alteration: '',
        size: '< 10 µm',
        coverage: '',
        environment: '',
        imageRefs: ['35A.1', '35A.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-031',
        title: 'Pits',
        type: 'Medium',
        agentsInvolved: '',
        morphologicalFeatures:
            'Pits of different shapes, distributed on the grain',
        origin: 'Mechanical/Chemical',
        factorsActing: '',
        alteration: '',
        size: '>10 µm - < 100 µm',
        coverage: '',
        environment: '',
        imageRefs: ['35B.1', '35B.2'],
      ),
      _createFeature(
        codeNumber: 'QMT-M-032',
        title: 'Pits',
        type: 'Large',
        agentsInvolved: '',
        morphologicalFeatures:
            'Pits of different shapes, distributed on the grain',
        origin: 'Mechanical/Chemical',
        factorsActing: '',
        alteration: '',
        size: '> 100 µm',
        coverage: '',
        environment: '',
        imageRefs: ['35C.1', '35C.2'],
      ),

      // Final Features (4)
      _createFeature(
        codeNumber: 'QMT-X-012',
        title: 'Fracture Planes/Plates',
        type: '',
        agentsInvolved: 'Wind transport and abrasion in the beach environment',
        morphologicalFeatures: 'Long crack of fracture on the surface',
        origin: 'Mechanical & Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: 'Eolian, Subaqueous',
        imageRefs: ['36A.1', '36A.2', '36A.3'],
      ),
      _createFeature(
        codeNumber: 'QMT-C-010',
        title: 'Etching',
        type: '',
        agentsInvolved: '',
        morphologicalFeatures:
            'Surface marked by etching minute pits distributed randomly or conform to grain crystallographic orientation. It may look like felted net of cavities',
        origin: 'Chemical',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: ['37A.1', '37A.2', '37A.3'],
      ),
    ];

    // Group features by title to create categories
    return _groupFeaturesByTitle(features);
  }

  static SedimentFeature _createFeature({
    required String codeNumber,
    required String title,
    required String type,
    required String agentsInvolved,
    required String morphologicalFeatures,
    required String origin,
    required String factorsActing,
    required String alteration,
    required String size,
    required String coverage,
    required String environment,
    required List<String> imageRefs,
  }) {
    return SedimentFeature(
      codeNumber: codeNumber,
      title: title,
      type: type,
      agentsInvolved: agentsInvolved,
      morphologicalFeatures: morphologicalFeatures,
      origin: origin,
      factorsActing: factorsActing,
      alteration: alteration,
      size: size,
      coverage: coverage,
      environment: environment,
      imageRefs: imageRefs,
    );
  }

  static List<SedimentFeature> _groupFeaturesByTitle(
    List<SedimentFeature> features,
  ) {
    final Map<String, List<SedimentFeature>> grouped = {};

    // Group features by title
    for (final feature in features) {
      grouped.putIfAbsent(feature.title, () => []).add(feature);
    }

    // Create category objects
    return grouped.entries.map((entry) {
      return SedimentFeature(
        codeNumber: entry.value.first.codeNumber,
        title: entry.key,
        type: '',
        agentsInvolved: '',
        morphologicalFeatures: '',
        origin: '',
        factorsActing: '',
        alteration: '',
        size: '',
        coverage: '',
        environment: '',
        imageRefs: [],
        isCategory: true,
        subFeatures: entry.value,
      );
    }).toList();
  }
}
